name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: '18.x'
      
      # - name: Enable Corepack
      #   run: corepack enable

      # - name: Install correct Yarn version
      #   run: corepack yarn set version 4.3.1
        
      # - name: Install dependencies
      #   run: yarn install

      - name: Install dependencies
        run: npm install

      - name: Lint code
        uses: github/super-linter@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: yarn test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/fast-food-tech-challenge:${{ github.sha }} .
          docker tag ghcr.io/${{ github.repository_owner }}/fast-food-tech-challenge:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/fast-food-tech-challenge:latest

      - name: Publish Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/fast-food-tech-challenge:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/fast-food-tech-challenge:latest
